spring:
  profiles:
    active:
    - dev
---
spring:
  profiles: dev #开发环境
  application:
    name: springcloud-config-cloudOne-dev
---
spring:
  profiles: test #测试环境
  application:
    name: springcloud-config-cloudOne-test

#注意：保存UTF-8格式