spring:
  profiles:
    active:
    - dev
---
server:
  port: 9401
spring:
  profiles: dev #开发环境
  application:
    name: springcloud-config-cloudOne-client
eureka:
  client:
    service-url:
      defaultZone: http://eureka9001-dev.com:9001/eureka/
---
server:
  port: 9402
spring:
  profiles: test #测试环境
  application:
    name: springcloud-config-cloudOne-client
eureka:
  client:
    service-url:
      defaultZone: http://eureka9001-test.com:9001/eureka/

#注意：保存UTF-8格式